name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: lab5
          file: lab5/Dockerfile
          push: true
          tags: your-registry/your-image-name:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull Docker image
        run: docker pull your-registry/your-image-name:latest

      - name: Run tests
        run: docker run your-registry/your-image-name:latest pytest
